### ISSUE TITLE
Line 2: "not_is_Norden" is not a known command

### ISSUE THREAD

**Issue by Kirua-Sama** [Entkenntnis/robot-karol-online#704] opened 2024-04-15 10:58 UTC
Assignment: Way Home - Heimweg
There is an Error in the english version when using "not_is_north" block
It seems the block uses the wrong function --> not_is_Norden

it actually applies to all directions: north, east, south and west

**Comment by Entkenntnis** [comment] 2024-04-16 09:20
Thank you for the report. I will look into it, I have an idea what the reason could be here.

**Comment by Entkenntnis** [comment] 2024-04-17 08:05
fixed in 85661ed2d716c4a0b90aca0b490455845ed509a0

**Comment by Entkenntnis** [comment] 2024-04-17 10:15
I can't not reproduce right now, can you refresh / hard refresh and send me some more information?

**Comment by Kirua-Sama** [comment] 2024-04-17 10:42
It is not exactly the same problem like previously

Here a simple test: 
![Screenshot 2024-04-17 at 12 39 30](https://github.com/Entkenntnis/robot-karol-online/assets/166800471/bc79a1f6-8f09-4c41-964f-74b38ef241d2)

**Comment by Entkenntnis** [comment] 2024-04-17 14:00
Thank you for the detailed report, I can now understand the problem

**Closed** 2024-04-17 20:06 UTC

**Comment by Kirua-Sama** [comment] 2024-04-18 09:54
works flawless now, thank you very much
